### ISSUE TITLE
running main.py got error RuntimeError: expected scalar type Int but found Long

### ISSUE THREAD

**Issue by jacklu2016** [tanimutomo/gcmc#26]
I have installed the required packages in requirement folder.But when running mian.py, i got error
`Processing...
Traceback (most recent call last):
  File "C:/Users/jack/PycharmProjects/gcmc/main.py", line 47, in <module>
    main(config)
  File "C:/Users/jack/PycharmProjects/gcmc/main.py", line 22, in main
    dataset = MCDataset(config.root, config.dataset_name)
  File "C:\Users\jack\PycharmProjects\gcmc\src\dataset.py", line 17, in __init__
    super(MCDataset, self).__init__(root, transform, pre_transform)
  File "C:\Users\jack\PycharmProjects\gcmc\venv\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 56, in __init__
    pre_filter)
  File "C:\Users\jack\PycharmProjects\gcmc\venv\lib\site-packages\torch_geometric\data\dataset.py", line 83, in __init__
    self._process()
  File "C:\Users\jack\PycharmProjects\gcmc\venv\lib\site-packages\torch_geometric\data\dataset.py", line 117, in _process
    self.process()
  File "C:\Users\jack\PycharmProjects\gcmc\src\dataset.py", line 75, in process
    edge_norm)
RuntimeError: expected scalar type Int but found Long`

**Comment by tanimutomo** [comment]
Sorry, I didnt check to run on windows properly.
I checked to run properly on ubuntu 16.04 and macOS.

Thanks.
